import axios from 'axios'

const api = axios.create({ baseURL: 'https://envirozone-v5.onrender.com', timeout: 60000 })

export const getDashboard      = () => api.get('/api/dashboard/summary')
export const getLineageGraph   = () => api.get('/api/lineage/graph')
export const getNodeDetail     = (id) => api.get(`/api/lineage/node/${id}`)
export const getNodeAI         = (id) => api.get(`/api/lineage/ai-summary/${id}`)
export const getModels         = () => api.get('/api/explainability/models')
export const getEstimates      = () => api.get('/api/explainability/estimates')
export const explainEstimate   = (id) => api.get(`/api/explainability/explain/${id}`)
export const semanticSearch    = (q) => api.get(`/api/explainability/search?query=${encodeURIComponent(q)}`)
export const getDataSources    = () => api.get('/api/quality/sources')
export const getAnomalies      = () => api.get('/api/quality/anomalies')
export const analyzeAnomaly    = (id) => api.get(`/api/quality/anomaly/${id}/analyze`)
export const resolveAnomaly    = (id, body) => api.put(`/api/quality/anomaly/${id}/resolve`, body)
export const getQualityRules   = () => api.get('/api/quality/rules')
export const getQualityTrend   = () => api.get('/api/quality/trend')
export const getAuditLogs      = () => api.get('/api/audit/logs')
export const getAuditSummary   = () => api.get('/api/audit/ai-summary')
export const getSuppliers      = () => api.get('/api/supplier/list')
export const addSupplier       = (data) => api.post('/api/supplier/add', data)
export const updateSupplierStatus = (id, body) => api.put(`/api/supplier/${id}/status`, body)
export const getSupplierRisk   = (id) => api.get(`/api/supplier/${id}/risk-analysis`)
export const getControls       = () => api.get('/api/reporting/controls')
export const getEmissions      = () => api.get('/api/reporting/emissions-summary')
export const getAIReadiness    = () => api.get('/api/reporting/ai-readiness')
export const generateReport    = (fw) => api.get(`/api/reporting/generate-report?framework=${fw}`)
export const uploadFile        = (fd) => api.post('/api/files/upload', fd, { headers:{'Content-Type':'multipart/form-data'}, timeout:120000 })
export const getFileTemplate   = () => api.get('/api/files/template')
export const getFileHistory    = (sid) => api.get(`/api/files/history${sid?'?supplier_id='+sid:''}`)
export const getFileDetail     = (id) => api.get(`/api/files/history/${id}`)
export const getAuthStandards  = () => api.get('/api/auth/standards')
export const authenticateFile  = (fd) => api.post('/api/auth/authenticate', fd, { headers:{'Content-Type':'multipart/form-data'}, timeout:120000 })
export const getCommodityBench = (c) => api.get(`/api/auth/benchmark/${c}`)
export const getEUDRChecklist  = (c) => api.get(`/api/auth/eudr-checklist/${c}`)

export default api
